### ISSUE TITLE
certain requests cause an internal server error

### ISSUE THREAD

**Issue by km-pg** [evansd/whitenoise#112]
Here's an example of a request that causes an internal server error because of whitenoise. If I comment out the DjangoWhiteNoise wrapper, this doesn't happen.

```
$ curl localhost:8000/%A3
<html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>
    
  </body>
</html>
```

```
Traceback (most recent call last):
  File "/Users/mulka/Documents/Code/gamzoo/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/mulka/Documents/Code/gamzoo/venv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/mulka/Documents/Code/gamzoo/venv/lib/python2.7/site-packages/whitenoise/base.py", line 60, in __call__
    path = decode_path_info(environ['PATH_INFO'])
  File "/Users/mulka/Documents/Code/gamzoo/venv/lib/python2.7/site-packages/whitenoise/utils.py", line 39, in decode_path_info
    return path_info.decode('utf-8')
  File "/Users/mulka/Documents/Code/gamzoo/venv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa3 in position 1: invalid start byte
```

**Comment by evansd** [comment]
@km-pg Thanks for reporting this.

**Comment by km-pg** [comment]
@evansd Thanks for fixing! We just deployed it.

**Comment by rdboyett** [comment]
I cant' get this to work with the latest whitenoise==3.3.0 with Django.  Collectstatic always error with this on bootstrap.css
```
Post-processed 'index/css/bootstrap.css' as 'index/css/bootstrap.530e39ffdffd.css'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 168, in handle
    collected = self.collect()
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/whitenoise/storage.py", line 67, in post_process
    for name, hashed_name, processed in files:
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/whitenoise/storage.py", line 29, in post_process_with_compression
    for name, hashed_name, processed in files:
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 321, in post_process
    for post_processed in all_post_processed:
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 240, in post_process
    content = original_file.read().decode(settings.FILE_CHARSET)
  File "/Users/robertboyett/Projects/ducksoup1/worksheet_project/venv/ducksoup/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x89 in position 359: invalid start byte
```

**Comment by evansd** [comment]
Hi @rdboyett,

This is a different error to the one reported in this ticket. The error you are getting is from Django itself because one of your files (whichever one comes _after_ `bootstrap.css`) contains invalid UTF8.

http://whitenoise.evans.io/en/stable/django.html#troubleshooting-the-whitenoise-storage-backend
