### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by EmadMokhtar** [evansd/whitenoise#115]
I have Django 1.10.4 installed and I tried to run `python manage.py collectstatic --noinput` command, I got `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

I tried to run the same command using Python 3.5, 3.6, 2.7.13 and Django 1.10.2 and still the same issue.

**Settings.py**

``` python
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
```

**Here is the full log**
```
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/cancel.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/change_form.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/popup_response.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Post-processed 'admin/css/base.css' as 'admin/css/base.ba3dc2f88fc5.css'
Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.b1b060f73d37.css'
Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.4898e2e9983d.css'
Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.cc6140298ba7.css'
Post-processed 'admin/css/forms.css' as 'admin/css/forms.70b858e61281.css'
Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.e024aaf6df25.css'
Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.a7251c097987.css'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 139, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/whitenoise/storage.py", line 67, in post_process
    for name, hashed_name, processed in files:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/whitenoise/storage.py", line 29, in post_process_with_compression
    for name, hashed_name, processed in files:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 333, in post_process
    for post_processed in all_post_processed:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 251, in post_process
    content = original_file.read().decode(settings.FILE_CHARSET)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by evansd** [comment]
What happens if you change the storage to:
```python
STATICFILES_STORAGE =  'django.contrib.staticfiles.storage.StaticFilesStorage'
```
And rerun with that?

**Comment by evansd** [comment]
OK, thanks. So it is an issue with WhiteNoise then. I'll look into it.

**Comment by evansd** [comment]
@EmadMokhtar I'm really sorry, I've just realised that I asked you to test the wrong thing. Can you try it with this setting instead:
```python
STATICFILES_STORAGE =  'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```

**Comment by EmadMokhtar** [comment]
@evansd Still the same issue

``` bash
Copying '/Users/Emad/Projects/halaqat/static/css/bootstrap-datetimepicker.min.css'
Copying '/Users/Emad/Projects/halaqat/static/css/bootstrap-rtl.css'
Copying '/Users/Emad/Projects/halaqat/static/css/bootstrap.min.css'
Copying '/Users/Emad/Projects/halaqat/static/fonts/glyphicons-halflings-regular.eot'
Copying '/Users/Emad/Projects/halaqat/static/fonts/glyphicons-halflings-regular.svg'
Copying '/Users/Emad/Projects/halaqat/static/fonts/glyphicons-halflings-regular.ttf'
Copying '/Users/Emad/Projects/halaqat/static/fonts/glyphicons-halflings-regular.woff'
Copying '/Users/Emad/Projects/halaqat/static/fonts/glyphicons-halflings-regular.woff2'
Copying '/Users/Emad/Projects/halaqat/static/js/bootstrap-datetimepicker.min.js'
Copying '/Users/Emad/Projects/halaqat/static/js/bootstrap.min.js'
Copying '/Users/Emad/Projects/halaqat/static/js/jquery.min.js'
Copying '/Users/Emad/Projects/halaqat/static/js/moment-with-locales.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/fonts.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/LICENSE.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/README.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Bold-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Light-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/fonts/Roboto-Regular-webfont.woff'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/calendar-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-addlink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-alert.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-calendar.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-changelink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-clock.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-deletelink.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-no.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown-alt.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-unknown.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/icon-yes.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/inline-delete.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/LICENSE'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/README.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/search.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/selector-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/sorting-icons.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-add.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.svg'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/cancel.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/change_form.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/popup_response.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/prepopulate_init.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/jquery.min.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/jquery/LICENSE-JQUERY.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/LICENSE-XREGEXP.txt'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.js'
Copying '/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/admin/static/admin/js/vendor/xregexp/xregexp.min.js'
Post-processed 'admin/js/vendor/jquery/jquery.js' as 'admin/js/vendor/jquery/jquery.aacc43d6f308.js'
Post-processed 'admin/js/vendor/jquery/jquery.min.js' as 'admin/js/vendor/jquery/jquery.min.33cabfa15c10.js'
Post-processed 'admin/js/vendor/jquery/LICENSE-JQUERY.txt' as 'admin/js/vendor/jquery/LICENSE-JQUERY.a158210a2737.txt'
Post-processed 'admin/js/vendor/xregexp/LICENSE-XREGEXP.txt' as 'admin/js/vendor/xregexp/LICENSE-XREGEXP.d64cecf4f157.txt'
Post-processed 'admin/js/vendor/xregexp/xregexp.js' as 'admin/js/vendor/xregexp/xregexp.1865b1cf5085.js'
Post-processed 'admin/js/vendor/xregexp/xregexp.min.js' as 'admin/js/vendor/xregexp/xregexp.min.c95393b8ca4d.js'
Post-processed 'admin/img/gis/move_vertex_off.svg' as 'admin/img/gis/move_vertex_off.7a23bf31ef8a.svg'
Post-processed 'admin/img/gis/move_vertex_on.svg' as 'admin/img/gis/move_vertex_on.0047eba25b67.svg'
Post-processed 'admin/js/admin/DateTimeShortcuts.js' as 'admin/js/admin/DateTimeShortcuts.1536fb6bea1d.js'
Post-processed 'admin/js/admin/RelatedObjectLookups.js' as 'admin/js/admin/RelatedObjectLookups.183db436487a.js'
Post-processed 'admin/css/base.css' as 'admin/css/base.ba3dc2f88fc5.css'
Post-processed 'admin/css/changelists.css' as 'admin/css/changelists.b1b060f73d37.css'
Post-processed 'admin/css/dashboard.css' as 'admin/css/dashboard.4898e2e9983d.css'
Post-processed 'admin/css/fonts.css' as 'admin/css/fonts.cc6140298ba7.css'
Post-processed 'admin/css/forms.css' as 'admin/css/forms.70b858e61281.css'
Post-processed 'admin/css/login.css' as 'admin/css/login.a846c0e2ef65.css'
Post-processed 'admin/css/rtl.css' as 'admin/css/rtl.e024aaf6df25.css'
Post-processed 'admin/css/widgets.css' as 'admin/css/widgets.a7251c097987.css'
Post-processed 'admin/fonts/LICENSE.txt' as 'admin/fonts/LICENSE.d273d63619c9.txt'
Post-processed 'admin/fonts/README.txt' as 'admin/fonts/README.2c3d0bcdede2.txt'
Post-processed 'admin/fonts/Roboto-Bold-webfont.woff' as 'admin/fonts/Roboto-Bold-webfont.2ad99072841e.woff'
Post-processed 'admin/fonts/Roboto-Light-webfont.woff' as 'admin/fonts/Roboto-Light-webfont.b446c2399bb6.woff'
Post-processed 'admin/fonts/Roboto-Regular-webfont.woff' as 'admin/fonts/Roboto-Regular-webfont.ec39515ae8c6.woff'
Post-processed 'admin/img/calendar-icons.svg' as 'admin/img/calendar-icons.39b290681a8b.svg'
Post-processed 'admin/img/icon-addlink.svg' as 'admin/img/icon-addlink.d519b3bab011.svg'
Post-processed 'admin/img/icon-alert.svg' as 'admin/img/icon-alert.034cc7d8a67f.svg'
Post-processed 'admin/img/icon-calendar.svg' as 'admin/img/icon-calendar.ac7aea671bea.svg'
Post-processed 'admin/img/icon-changelink.svg' as 'admin/img/icon-changelink.18d2fd706348.svg'
Post-processed 'admin/img/icon-clock.svg' as 'admin/img/icon-clock.e1d4dfac3f2b.svg'
Post-processed 'admin/img/icon-deletelink.svg' as 'admin/img/icon-deletelink.564ef9dc3854.svg'
Post-processed 'admin/img/icon-no.svg' as 'admin/img/icon-no.439e821418cd.svg'
Post-processed 'admin/img/icon-unknown-alt.svg' as 'admin/img/icon-unknown-alt.81536e128bb6.svg'
Post-processed 'admin/img/icon-unknown.svg' as 'admin/img/icon-unknown.a18cb4398978.svg'
Post-processed 'admin/img/icon-yes.svg' as 'admin/img/icon-yes.d2f9f035226a.svg'
Post-processed 'admin/img/inline-delete.svg' as 'admin/img/inline-delete.fec1b761f254.svg'
Post-processed 'admin/img/LICENSE' as 'admin/img/LICENSE.2c54f4e1ca1c'
Post-processed 'admin/img/README.txt' as 'admin/img/README.837277fa1908.txt'
Post-processed 'admin/img/search.svg' as 'admin/img/search.7cf54ff789c6.svg'
Post-processed 'admin/img/selector-icons.svg' as 'admin/img/selector-icons.b4555096cea2.svg'
Post-processed 'admin/img/sorting-icons.svg' as 'admin/img/sorting-icons.3a097b59f104.svg'
Post-processed 'admin/img/tooltag-add.svg' as 'admin/img/tooltag-add.e59d620a9742.svg'
Post-processed 'admin/img/tooltag-arrowright.svg' as 'admin/img/tooltag-arrowright.bbfb788a849e.svg'
Post-processed 'admin/js/actions.js' as 'admin/js/actions.32861b6cbdf9.js'
Post-processed 'admin/js/actions.min.js' as 'admin/js/actions.min.f51f04edab28.js'
Post-processed 'admin/js/calendar.js' as 'admin/js/calendar.9ac94d055fbd.js'
Post-processed 'admin/js/cancel.js' as 'admin/js/cancel.1d69cba4b4bf.js'
Post-processed 'admin/js/change_form.js' as 'admin/js/change_form.d224f77c6b61.js'
Post-processed 'admin/js/collapse.js' as 'admin/js/collapse.17d715df2104.js'
Post-processed 'admin/js/collapse.min.js' as 'admin/js/collapse.min.dc930adb2821.js'
Post-processed 'admin/js/core.js' as 'admin/js/core.fd861d43f0f5.js'
Post-processed 'admin/js/inlines.js' as 'admin/js/inlines.17981b4df24a.js'
Post-processed 'admin/js/inlines.min.js' as 'admin/js/inlines.min.8ef8b2379896.js'
Post-processed 'admin/js/jquery.init.js' as 'admin/js/jquery.init.95b62fa19378.js'
Post-processed 'admin/js/popup_response.js' as 'admin/js/popup_response.6ce3197f8fc8.js'
Post-processed 'admin/js/prepopulate.js' as 'admin/js/prepopulate.ff9208865444.js'
Post-processed 'admin/js/prepopulate.min.js' as 'admin/js/prepopulate.min.f4057ebb9b62.js'
Post-processed 'admin/js/prepopulate_init.js' as 'admin/js/prepopulate_init.0d3b53c37074.js'
Post-processed 'admin/js/SelectBox.js' as 'admin/js/SelectBox.b49f008d186b.js'
Post-processed 'admin/js/SelectFilter2.js' as 'admin/js/SelectFilter2.17009b6d4428.js'
Post-processed 'admin/js/timeparse.js' as 'admin/js/timeparse.51258861a46a.js'
Post-processed 'admin/js/urlify.js' as 'admin/js/urlify.411bc3bb651c.js'
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 193, in handle
    collected = self.collect()
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 139, in collect
    for original_path, processed_path, processed in processor:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 333, in post_process
    for post_processed in all_post_processed:
  File "/Users/Emad/virtualenv/halaqat/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 251, in post_process
    content = original_file.read().decode(settings.FILE_CHARSET)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by evansd** [comment]
OK, thanks. If you still get the issue using `ManifestStaticFilesStorage` then it means the issue is with Django itself and not with WhiteNoise. You could try asking for help on the [Django users](https://docs.djangoproject.com/en/dev/internals/mailing-lists/#django-users) mailing list. It might turn out to be a bug in Django, or just an encoding problem with one of your files.
