### ISSUE TITLE
static file permission denied during collectstatic

### ISSUE THREAD

**Issue by DoubleCouponDay** [evansd/whitenoise#186]
I am using whitenoise to distribute static content. during an execution of runserver, in a development environment, I have the misfortune of experiencing a failed build due to file locks on static files. The only way to fix the issue is to remove the file so this is not feasible in production.

```
Post-processed 'admin\css\vendor\select2\select2.min.css' as 'admin/css/vendor/select2/select2.min.d44571114a90.css'
Traceback (most recent call last):
  File "C:\Users\sjsui\Desktop\git_workshop\MoonMachineProprietary\herokuproprietary\herokuproprietary\MoonMachine\MoonMachine/manage.py", line 26, in <module>
    execute_from_command_line([os.path.join(BASE_DIR, "manage.py"), "collectstatic", "--no-input"])
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 189, in handle
    collected = self.collect()
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\contrib\staticfiles\management\commands\collectstatic.py", line 129, in collect
    for original_path, processed_path, processed in processor:
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\pipeline\storage.py", line 39, in post_process
    for name, hashed_name, processed in super_class.post_process(paths.copy(), dry_run, **options):
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\contrib\staticfiles\storage.py", line 246, in post_process
    for name, hashed_name, processed, subst in self._post_process(paths, adjustable_paths, hashed_files):
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\contrib\staticfiles\storage.py", line 310, in _post_process
    saved_name = self._save(hashed_name, content_file)
  File "C:\Users\sjsui\.virtualenvs\MoonMachine-oZ6UWPMB\lib\site-packages\django\core\files\storage.py", line 264, in _save
    fd = os.open(full_path, flags, 0o666)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\sjsui\\Desktop\\git_workshop\\MoonMachineProprietary\\herokuproprietary\\herokuproprietary\\MoonMachine\\MoonMachine\\static\\admin\\css\\autocomplete.781713f30664.css'
```

**Comment by evansd** [comment]
Do you get the same issue if you use Django's built-in static file storage? In `settings.py` try using this instead:
```
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
```
If you still get the problem then it's an issue with Django and not anything specific to WhiteNoise.

**Comment by DoubleCouponDay** [comment]
This bug is not easily reproducable but ill see what I can find.

Sincerely,
Sam

**Comment by evansd** [comment]
Closing for lack of activity

**Comment by pyth0nkod3r** [comment]
I get the below error whenever I run "python manage.py collectstatic"  
 Using the default Django storage engine gives no error. I'm using whitenoise v6.1.0.
I've given my static folder full permissions, yet the error persists                                                                                             

"""
You have requested to collect static files at the destination
location as specified in your settings:                                                          /storage/emulated/0/django/test_e/staticfiles                                                                     This will overwrite existing files!
Are you sure you want to do this?                          
Type 'yes' to continue, or 'no' to cancel: yes             Traceback (most recent call last):                           File "/storage/emulated/0/django/test_e/manage.py", line 22, in <module>                                                main()
  File "/storage/emulated/0/django/test_e/manage.py", line 18, in main                                                    execute_from_command_line(sys.argv)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()                                        File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute             self.fetch_command(subcommand).run_from_argv(self.argv)  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)                       File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 148, in collect
    for original_path, processed_path, processed in processor:
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/storage.py", line 162, in post_process_with_compression
    for name, compressed_name in self.compress_files(files_to_compress):
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/storage.py", line 199, in compress_files
    for compressed_path in compressor.compress(path):
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/compress.py", line 77, in compress
    yield self.write_data(path, compressed, ".br", stat_result)
  File "/data/data/com.termux/files/home/.local/share/virtualenvs/test_e-SjLmU3eY/lib/python3.10/site-packages/whitenoise/compress.py", line 122, in write_data
    os.utime(filename, (stat_result.st_atime, stat_result.st_mtime))
PermissionError: [Errno 1] Operation not permitted
"""
