### ISSUE TITLE
Problem with collect static on start deploying with django

### ISSUE THREAD

**Issue by dnl-krsvch** [evansd/whitenoise#246]
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "manage.py", line 21, in <module>
           main()
         File "manage.py", line 17, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 161, in handle
           if self.is_local_storage() and self.storage.location:
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 215, in is_local_storage
           return isinstance(self.storage, FileSystemStorage)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/functional.py", line 224, in inner
           self._setup()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 501, in _setup
           self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 359, in get_storage_class
           return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
           module = import_module(module_path)
         File "/app/.heroku/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 994, in _gcd_import
         File "<frozen importlib._bootstrap>", line 971, in _find_and_load
         File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 678, in exec_module
         File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
         File "/app/.heroku/python/lib/python3.6/site-packages/whitenoise/django.py", line 2, in <module>
           "\n\n"
       ImportError: 
       Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
       This can be fixed by following the upgrade instructions at:
       http://whitenoise.evans.io/en/stable/changelog.html#v4-0
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by evansd** [comment]
As it says in the error message above:

> Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
> This can be fixed by following the upgrade instructions at:
> http://whitenoise.evans.io/en/stable/changelog.html#v4-0
