### ISSUE TITLE
Using Whitenoise in docker container fails due to "OSError: [Errno 40] Too many levels of symbolic links"

### ISSUE THREAD

**Issue by terranblake** [evansd/whitenoise#276]
Whitenoise works perfectly fine running locally, but when deployed in a docker container, using this simple dockerfile
```
FROM python:3.9

COPY requirements.txt /requirements.txt
RUN pip install --upgrade setuptools
RUN pip install -r /requirements.txt

ADD . /usr
WORKDIR /usr
```
I receive the following error complaining about a never-ending chain of symbolic links
```
Traceback (most recent call last):
  File "map-viewer.py", line 44, in <module>
    app.wsgi_app = WhiteNoise(
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 76, in __init__
    self.add_files(root, prefix)
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 113, in add_files
    self.update_files_dictionary(root, prefix)
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 120, in update_files_dictionary
    stat_cache = dict(scantree(root))
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 271, in scantree
    yield from scantree(entry.path)
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 271, in scantree
    yield from scantree(entry.path)
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 271, in scantree
    yield from scantree(entry.path)
  [Previous line repeated 35 more times]
  File "/usr/local/lib/python3.8/site-packages/whitenoise/base.py", line 270, in scantree
    if entry.is_dir():
OSError: [Errno 40] Too many levels of symbolic links: '/usr/bin/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/X11/cc'
```
I was able to resolve this issue on my end by breaking that loop. This does not resolve the issue internal to whitenoise though. The line I added to my dockerfile to accomplish this is:
```
RUN rm /usr/bin/X11/X11
```

**Comment by adamchainz** [comment]
That sounds like you had a recursive symlink, and you pointed Whitenoise at it. Many programs will break with recursive symlinks, I don't think Whitenoise should handle them.

I think you probably didn't want to place your application in `/usr` (a special unix folder) and serve assets from there. The normal way is to put your application in `/opt/<appname>`, because `/opt` is reserved for user applications, and won't be used by the OS.
