### ISSUE TITLE
ModuleNotFoundError: No module named 'whitenoise'

### ISSUE THREAD

**Issue by developershohel** [evansd/whitenoise#427]
### Python Version

3.6.8

### Django Version

3.2.0

### Package Version

1.0.0

### Description

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib64/python3.6/site-packages/django/apps/config.py", line 224, in create
    import_module(entry)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'whitenoise'

**Comment by merwok** [comment]
… Have you installed whitenoise?

**Comment by adamchainz** [comment]
Yes you must be missing the installation.

**Comment by adamchainz** [comment]
You’re likely not running Python from within the right virtualenv. If you run `python -m pip freeze` you should see whitenoise listed. `python -c 'import whitenoise'` should work. If not, please try removing and resetting up your virtualenv.

I cannot support such a basic problem any further. Search the web for resources on creating and using virtualenvs.
