### ISSUE TITLE
HTTP Backport doesn't have METHOD_NOT_ALLOWED

### ISSUE THREAD

**Issue by g3rd** [evansd/whitenoise#92]
When I run any management command, ex: `./manage.py collectstatic`, I am seeing

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/www/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/www/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/www/venv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/www/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/www/venv/local/lib/python2.7/site-packages/debug_toolbar/apps.py", line 16, in ready
    dt_settings.check_middleware()
  File "/home/www/venv/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 164, in check_middleware
    if is_middleware_class(GZipMiddleware, middleware):
  File "/home/www/venv/local/lib/python2.7/site-packages/debug_toolbar/settings.py", line 179, in is_middleware_class
    middleware_cls = import_string(middleware_path)
  File "/home/www/venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/www/venv/local/lib/python2.7/site-packages/whitenoise/__init__.py", line 1, in <module>
    from .base import WhiteNoise
  File "/home/www/venv/local/lib/python2.7/site-packages/whitenoise/base.py", line 8, in <module>
    from .static_file import StaticFile
  File "/home/www/venv/local/lib/python2.7/site-packages/whitenoise/static_file.py", line 15, in <module>
    NOT_ALLOWED = Response(HTTPStatus.METHOD_NOT_ALLOWED,
  File "/home/www/venv/local/lib/python2.7/site-packages/whitenoise/httpstatus_backport.py", line 31, in __getattr__
    code = getattr(status_module, status)
AttributeError: 'module' object has no attribute 'METHOD_NOT_ALLOWED'
```

Environment:
* Whitenoise 3.2
* Python 2.7.6

**Comment by evansd** [comment]
There's something very strange going on here. The `httplib` module in Python 2.7.6 definitely has that attribute (as shown in [the source](https://hg.python.org/cpython/file/99d03261c1ba/Lib/httplib.py#l135)). I wonder if you've got another module called `httplib` or `http` on your path somewhere that's shadowing the stdlib module.

If you open a Python console using the same version of Python but outside of your virtualenv and run:
```
import httplib
print httplib.METHOD_NOT_ALLOWED
```
What do you get? What do you get if you run the same thing but inside of your project's venv?

**Comment by evansd** [comment]
I've just tested this against Python 2.7.6 with a clean WhiteNoise install and there are no issues, so this is  definitely something specific to your project setup.

Do please update the issue here once you find the solution (even if it turns out the be something stupid ;) as it would be useful to know what's causing this.

**Comment by g3rd** [comment]
I fixed my issue, something I had installed had `http` module.

However, shouldn't `httpstatus_backport.py` have a `METHOD_NOT_ALLOWED` attribute?

What is the Whitenoise Python requirements?

**Comment by evansd** [comment]
WhiteNoise doesn't have any dependencies outside the standard library. For older versions of Python that don't have the `HTTPStatus` enum it uses the constants from either `http.client` (for Python 3.3) or `httplib` (for Python 2) rather than defining them itself.

**Comment by edmorley** [comment]
> I fixed my issue, something I had installed had http module.

Do you know what package had the dependency on it, and so caused it to be installed?
